name: 新功能反馈
description: 提交你想要的新功能
labels: ["feature"]
assignees:
  - JWJUN233233
body:
  - type: markdown
    attributes:
      value: |
        ## 欢迎来到 TimetownDev 的功能反馈器
        你正在反馈希望在 SlimeAE 出现的新功能。

        <strong><i>你必须填写标注为星号（*）的表单项</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查项目
      description: 在汇报之前，你需要确认
      options:
        - label: 你使用的是从构建站下载的版本
          required: false
        - label: 你没有对下载的文件内容进行任何更改
          required: true
        - label: 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题
          required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: |
        详细描述你要的新功能
        提供详细的信息能让我们更快 准确地完成新功能
    validations:
      required: true
